name: Auto-Update Tamil M3U

permissions:
  contents: write

on:
  workflow_dispatch:
  schedule:
    - cron: '*/30 * * * *'

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main branch
        uses: actions/checkout@v4
        with:
          ref: main
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Install jq
        run: sudo apt-get update && sudo apt-get install -y jq

      - name: Generate tamil.m3u
        run: |
          echo "📥 Fetching Jiotv.json..."
          JSON_URL="https://playify.pages.dev/Jiotv.json"
          JSON=$(curl -sf \
            -H "User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/119.0.0.0 Safari/537.36" \
            -H "Accept: application/json" \
            -H "Referer: https://playify.pages.dev/" \
            "$JSON_URL") || { echo "❌ Failed to fetch JSON"; exit 1; }
          if [ -z "$JSON" ] || [ "${JSON:0:1}" = "<" ]; then
            echo "❌ Response is empty or HTML"
            exit 1
          fi
          echo "#EXTM3U" > tamil.m3u
          # ✅ YOUR FINAL 31 CHANNELS — exact names, case-insensitive match
          echo "$JSON" | jq -r '
            def channels:
              if type == "array" then .
              elif type == "object" then
                if has("channels") and (.channels | type == "array") then .channels
                elif has("data") and (.data | type == "array") then .data
                elif has("list") and (.list | type == "array") then .list
                elif (.[] | type == "object") then [.[]]
                else []
                end
              else []
              end;
            # Your 31 exact channel names
            [
              "Sun TV HD",
              "Sun Music HD",
              "Sun Life",
              "Adithya TV",
              "KTV HD",
              "Star Vijay HD",
              "Vijay Super HD",
              "Colors Tamil",
              "Jaya TV HD",
              "Jaya Plus",
              "Jaya Max",
              "J Movies",
              "Polimer TV",
              "Vasanth TV",
              "Kalaignar TV",
              "Raj TV",
              "Disney",
              "Disney Junior",
              "Hungama TV",
              "Super Hungama",
              "Sonic Tamil",
              "Nick Tamil",
              "Nickelodeon Jr.",
              "Pogo",
              "Cartoon Network",
              "CN HD+ Tamil",
              "Discovery Kids Tamil",
              "D Tamil",
              "History HD"
            ] as $list |
            channels as $all |
            $list[] as $target |
            # Find FIRST channel whose name (case-insensitive) matches $target EXACTLY
            ($all | map(select(
              (.name // .title // "") | ascii_downcase == ($target | ascii_downcase)
            )) | .[0]) as $match |
            # Only output if match exists AND has link
            if ($match | type == "object") and ($match.link // $match.url // "") != "" then
              $match |
              (.name // .title // $target) as $name |
              (.tvg_id // .tvgId // .id // "") as $tvg_id |
              (.tvg_logo // .logo // .icon // "") as $tvg_logo |
              (.drmScheme // .drm_scheme // .drm // "") as $drmScheme |
              (.drmLicense // .license // "") as $drmLicense |
              (.cookie // .cookies // "") as $cookie |
              (.link // .url // .stream_url // .hls // .mpd // "") as $link |
              "#EXTINF:-1 " +
                (if ($tvg_id | length > 0) then "tvg-id=\"\($tvg_id)\" " else "" end) +
                "group-title=\"Tamil\" " +
                (if ($tvg_logo | length > 0) then "tvg-logo=\"\($tvg_logo)\" " else "" end) +
                ",\($name | gsub(","; "\\,"))" |
              . as $extinf |
              (if ($drmScheme == "clearkey") and ($drmLicense | test("^[a-zA-Z0-9]+:[a-zA-Z0-9]+")) then
                "#KODIPROP:inputstream.adaptive.license_type=clearkey\n#KODIPROP:inputstream.adaptive.license_key=" + 
                ($drmLicense | split(":")[0:2] | join(":"))
              else "" end) as $drm |
              "#EXTVLCOPT:http-user-agent=plaYtv/7.1.5%20(Linux%3BAndroid%2015)%20ExoPlayerLib/2.11.6%20YGX/69.69.69.69" as $ua |
              (if ($cookie | length > 0) then
                "#EXTHTTP:{\"cookie\":\"" + ($cookie | gsub("\""; "\\\"")) + "\"}"
              else "" end) as $cookie_line |
              [
                $extinf,
                ($drm | select(. != "")),
                $ua,
                ($cookie_line | select(. != "")),
                $link
              ] | join("\n")
            else empty end
          ' >> tamil.m3u
          # Final report
          TOTAL=$(grep -c "^#EXTINF" tamil.m3u || echo 0)
          echo "✅ tamil.m3u created: $TOTAL / 31 channels found"
          if [ "$TOTAL" -gt 0 ]; then
            echo "📋 Channels included:"
            grep "^#EXTINF" tamil.m3u | sed 's/.*,//'
          else
            echo "❌ None of the 31 channels were found in Jiotv.json"
            echo "🔍 Top 20 channel names in JSON:"
            echo "$JSON" | jq -r 'channels | .[0:20][] | .name // .title // "–"' 2>/dev/null
            exit 1
          fi
      - name: Commit & Push
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add tamil.m3u
          if git diff --cached --quiet; then
            echo "➡️ No changes — skipping commit"
            exit 0
          fi
          git commit -m "✅ Auto-update Tamil M3U: $TOTAL/31 channels | $(date -u '+%Y-%m-%d %H:%M')"
          git push origin main
